package Acme::CPANLists::Import::PerlAdvent::2010;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2010/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"YAPE::Regex::Explain"},{module=>"Set::Array"},{module=>"Win32::GUI"},{module=>"Devel::Eval"},{module=>"Champlain"},{module=>"install"},{module=>"selfvars"},{module=>"Carp::REPL"},{module=>"Dumpvalue"},{module=>"App::perlzonji"},{module=>"Tkx"},{module=>"Perl::MinimumVersion"},{module=>"Env::Sanctify"},{module=>"Env::Sanctify::Auto"},{module=>"Net::Server"},{module=>"Math::Geometry::Voronoi"},{module=>"Text::BarGraph"},{module=>"Whatever"},{module=>"Net::Twitter"},{module=>"Net::Twitter::Lite"},{module=>"Benchmark::Timer"},{module=>"Digest::BubbleBabble"},{module=>"Package::Stash"},{module=>"Text::ParagraphDiff"}],summary=>"Modules mentioned in Perl Advent Calendar 2010"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2010

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2010/> (retrieved on 2016-11-07). Visit the URL for the full contents.

