package Acme::CPANLists::Import::PerlAdvent::2010_12_03;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2010/3/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Win32::GUI"}],summary=>"Modules mentioned in Perl Advent Calendar 2010 (day 3)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2010 (day 3)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2010/3/> (retrieved on 2016-11-07). Visit the URL for the full contents.

